# config/tasks.yaml
discovery_task:
  description: >
    Expand this initial list of potential buyers: {seed_list}
    
    Using geography ({target_regions}) and AUM criteria (minimum {min_aum}), identify additional 
    qualified buyers that might be interested in acquiring a company in the {target_industry} industry.
    
    For each potential buyer you find:
    1. Obtain their name, website URL, location, and primary industry focus
    2. Focus specifically on family offices and private equity funds that match our criteria
    3. Include firms that have made acquisitions in related sectors in the past 24 months
    
    Use both Exa.ai and Serper search tools to ensure comprehensive coverage. Your goal is to 
    discover high-quality potential buyers that might not be on typical radar.
  expected_output: >
    A refined list of at least 15-20 potential buyers with their names, 
    website URLs, locations, and primary industry focuses. Format the output 
    as a structured JSON array, with each entry containing the fields: 
    name, url, location, industry_focus, type (family office/PE fund/other).
  agent: discovery_agent

profile_scraper_task:
  description: >
    For each buyer URL in this list: {buyer_urls}
    
    Visit their website and extract comprehensive profile information including:
    1. Low-level data: Full address, contact email, founding year, key leadership team members and their roles
    2. High-level data: Investment thesis, target sectors, geographic preferences, typical investment size,
       cultural values, and any specific statements about acquisition criteria
    
    Structure this information in a consistent format for each buyer. Pay particular attention to 
    any mentions of previous investments or acquisitions in the {target_industry} industry or related 
    sectors. Look for information that indicates their investment approach and decision-making criteria.
    
    Use the FirecrawlScrapeWebsiteTool to efficiently extract content from each website.
  expected_output: >
    Detailed, structured profiles for each buyer in JSON format, with consistent fields
    across all entries, capturing both factual information and investment approach insights.
    Include a "match_factors" field for each buyer that lists specific elements that might
    make them a good match for a company in the {target_industry} industry.
  agent: profile_scraper_agent
  context:
    - discovery_task

news_scraper_task:
  description: >
    For each buyer in this list: {buyer_names}
    
    Research and collect recent news articles, press releases, and media coverage related
    to their investment activities from the past 24 months. Focus particularly on:
    1. Recent acquisitions or investments
    2. Fundraising activities
    3. Changes in investment strategy
    4. Executive team changes
    5. Statements about future plans or sectors of interest
    
    Pay special attention to any mentions related to the {target_industry} industry or
    adjacent sectors. Analyze the collected information to identify patterns in their
    investment behavior and potential interest in our target company.
    
    Use Serper and Exa.ai search tools to find relevant news across multiple sources.
  expected_output: >
    A comprehensive media overview for each buyer, including structured summaries of
    relevant news items, publication dates, and key insights about their
    recent activity patterns. Format as JSON with fields for each buyer including:
    name, recent_acquisitions, fundraising_events, strategy_changes, key_personnel_changes, 
    and sector_interests. Add a "relevance_score" field (1-10) indicating how aligned 
    their recent activities are with {target_industry}.
  agent: news_scraper_agent
  context:
    - profile_scraper_task