# config/tasks.yaml
discovery_task:
 description: >
   Conduct thorough research to identify family office investors located within a 300-mile radius of Chicago, Illinois that have Assets Under Management (AUM) of $100 million or more.
  
   Focus on genuine family offices that manage substantial wealth for ultra-high-net-worth families,
   not wealth management firms that merely use "family office" in their marketing.
  
   For each family office discovered:
   1. Obtain their name
   2. Find their official website URL (if available)
   3. Note their location (can be anywhere within 300 miles of Chicago)
   4. Identify any available information about their AUM (must be $100M+)
   5. Identify any available information about their investment focus
  
   IMPORTANT: When using the EXASearchTool, be sure to use the correct format with the 'search_query' parameter.
   For example: {"search_query": "family offices within 300 miles of Chicago $100+ million AUM"}
  
   Perform multiple searches with different queries to ensure comprehensive coverage, such as:
   - "family office investors 300 miles Chicago $100 million AUM"
   - "family offices near Chicago large AUM Michigan Wisconsin Indiana"
   - "private investment offices midwest substantial assets"
   - "single family offices Illinois Wisconsin Michigan Indiana high net worth"
   - "multi-family offices midwest $100M+"
   - "ultra high net worth family offices Chicago area"
   - "Chicago area wealthy family investment offices Milwaukee Detroit"
  
   Aim to find as many legitimate family offices within the 300-mile radius as possible. If your first search doesn't yield enough results,
   try additional search queries.
  
   Use the EXA search tool to comprehensively search across multiple sources.
   Verify each entity you find is truly a family office (not a wealth management firm) AND likely has AUM of at least $100 million.
  
   Cities within 300 miles of Chicago include Milwaukee, Indianapolis, Detroit, Madison, Grand Rapids, Cincinnati, Cleveland, and others.
  
   Note: For family offices that don't publicly disclose their AUM, look for indirect indicators such as:
   - Size and value of known investments
   - Number of staff/professionals
   - Size and prestige of office location
   - Notable wealthy families associated with the office
   - Language indicating "substantial wealth" or similar terms
  
 expected_output: >
   A structured JSON array containing family offices within 300 miles of Chicago with
   their names, website URLs, locations, approximate AUM (when available), and investment focus.
   Each entry should include fields: name, url, location, estimated_aum, investment_focus, and a
   confidence_score (1-10) indicating your confidence that this is a legitimate family office with AUM of $100M+.
   Include an aum_evidence field that briefly explains your reasoning for believing the family office meets the $100M+ threshold.
 agent: family_office_discovery_agent


profile_scraper_task:
 description: >
   For each family office URL in this list: {discovered_offices}
  
   IMPORTANT: You must process ALL family offices in the list, not just the first one.
   
   For each family office, you need to scrape multiple specific pages to gather complete information:
   
   1. First, scrape the main website URL to get general information
   2. Then, explicitly check these common contact/team pages (modify the URL as needed):
      - Main domain URL (e.g., https://example.com)
      - Contact page (e.g., https://example.com/contact or https://example.com/contact-us)
      - About page (e.g., https://example.com/about or https://example.com/about-us)
      - Team page (e.g., https://example.com/team or https://example.com/leadership or https://example.com/people)
      - Footer section of the main page (often contains contact info)
   
   For each family office, extract:
   1. Contact information: Full address, phone number, email (if available)
   2. Team members: Names, titles, and roles of as many team members as you can find
   3. AUM data: Any direct or indirect information about Assets Under Management
   4. Investment details: Philosophy, target sectors, geographic preferences, typical investment size, etc.
   
   IMPORTANT: For each website, you must make MULTIPLE separate scraping requests:
   1. One for the main domain
   2. One specifically for the contact page
   3. One for the about/team page
   
   This approach will ensure you get complete information even if the FirecrawlScrapeWebsiteTool has limitations.
   
   Structure this information in a consistent format for each family office.
   
   Make sure to return ALL family offices in your response, not just the first one.
 expected_output: >
   Detailed, structured profiles for EACH family office in JSON format, with consistent fields
   across all entries, capturing both factual information, team members when available, and investment approach insights.
   Include an "aum_estimate" field with your best estimate of their AUM (if available) and an
   "aum_evidence" field explaining what information supports this estimate.
   Include a "team_members" array that lists any identified team members with their names and roles when available.
   Include a "completeness_score" field for each profile (1-10) that indicates how complete
   the profile information is based on available data.
   
   Your output MUST include ALL family offices from the input list, not just the first one.
 agent: family_office_profile_agent
 context:
   - discovery_task

news_scraper_task:
 description: >
   For each family office profiled in the previous task: {profiled_offices}
  
   Research and collect recent news articles, press releases, and media coverage related to these family offices from the past 10 years.
   
   IMPORTANT: Your final output MUST be valid JSON. Double-check your formatting before submitting.
   
   Focus particularly on:
   1. Recent acquisitions or investments (past 10 years)
   2. Fundraising activities
   3. Changes in investment strategy
   4. Executive team changes
   5. Expansion into new markets
   6. Partnerships or collaborations
  
   Use the SerperDevTool to search for each family office's name along with relevant keywords such as:
   - "[family office name] investment 2014..2024"
   - "[family office name] acquisition 2014..2024"
   - "[family office name] fundraising 2014..2024"
   - "[family office name] private equity 2014..2024"
   - "[family office name] leadership change 2014..2024"
   - "[family office name] news 2014..2024"
   - "[family office name] press release 2014..2024"
  
   When using SerperDevTool, be sure to use the search_query parameter correctly:
   For example: {"search_query": "Pritzker Organization acquisition 2014..2024"}
  
   For each family office, compile:
   1. A summary of activities over the past 10 years (2014-2024)
   2. Any notable transactions or investments
   3. Changes in strategy or focus areas
   4. Important leadership or organizational changes
   
   IMPORTANT: For each article or news item found, you must:
   1. Visit the source URL to extract the full text of the article
   2. Store the complete article text in your output
   3. Ensure you're gathering at least 3-5 articles per family office when available
   
   If little or no news is found for a family office, note this and provide whatever limited information you can find.
  
 expected_output: >
   A structured JSON array containing news intelligence on each family office, including:
   
   [
     {
       "name": "Family Office Name",
       "recent_activities": [
         {
           "date": "YYYY-MM-DD", 
           "headline": "Brief headline or summary",
           "description": "Detailed description of the activity",
           "source": "Source of the information (e.g., website name)",
           "url": "URL to the news source (if available)",
           "activity_type": "acquisition|investment|fundraising|leadership_change|strategy_shift|other",
           "full_text": "The complete text of the article or press release"
         }
       ],
       "key_transactions": [
         {
           "date": "YYYY-MM-DD",
           "transaction_type": "acquisition|investment|partnership",
           "target": "Name of the acquired/invested company",
           "amount": "Dollar amount if available",
           "description": "Brief description of the transaction"
         }
       ],
       "strategy_insights": "Analysis of the family office's investment strategy based on news",
       "leadership_changes": "Notable leadership changes in the past 10 years",
       "news_presence_score": 7 // 1-10 scale indicating how active/visible the family office is in news
     }
   ]
   
   Keep the structure consistent but note that some family offices may have minimal or no news coverage.
   In such cases, provide what information is available and note the limited news presence.
   
 agent: family_office_news_agent
 context:
   - profile_scraper_task